spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/
zuul:
  # 服务重定向时,控制服务经过api-gateway转发
  addHostHeader: true
  # 前缀
  prefix: /api
  # 前缀开启,默认
  strip-prefix: true
  routes:
    a:
      # 将/aaa/** 转发到当前应用local中
      path: /aaa/**
      url: "forward:/local"
    # 自定义映射，?：单字符,*：任意字符，**：任意字符包含子级
    producer: /a/**
  # 忽略指定服务
  ignored-services: producer
  # 忽略指定服务的指定路径
  # ignored-patterns: "/**/a/producer/findUsers/**"
management:
  security:
    web:
      exposure:
        include: "*"
# zuul模块包含ribbon和hystrix依赖
# 可以配置ribbon和hystrix所有配置
# 全局关闭重试机制
#zuul:
#  retryable: false