#  profiles:
#    active: peer2
spring:
  profiles:
    active: peer1
eureka:
  server:
    # 关闭注册中心的保护机制
    enable-self-preservation: false
    # 设置清理失效服务间隔时间
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: localhost
  client:
    # 应用为注册中心,启动后不注册自己
    #register-with-eureka: false
    # 设置不去服务中心获取服务,eureka-server作为服务中心不需要向自己获取
    #fetch-registry: false
    #serviceUrl:
    #  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
