server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    # 应用为注册中心,启动后不注册自己
    register-with-eureka: true
    # 不去检索自己的服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
