spring:
  application:
    name: feign
  rabbitmq:
    username: springcloud
    password: springcloud
server:
  port: 2500
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/
ribbon:
  readTimeout: 5000
  connectTimeout: 5000
logging:
  level:
    com:
      hks:
        feign:
          service: debug
feign:
  hystrix:
    enabled: true